(()=>{
const S=(body,w=640,h=280)=>`<svg viewBox="0 0 ${w} ${h}" role="img" xmlns="http://www.w3.org/2000/svg">${body}</svg>`;
const box=(x,y,w,h,label,sub='')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="16" fill="#f7fafc" stroke="#9eb3c7" stroke-width="2"/><text x="${x+w/2}" y="${y+h/2-4}" text-anchor="middle" class="v-label">${label}</text>${sub?`<text x="${x+w/2}" y="${y+h/2+20}" text-anchor="middle" class="v-small">${sub}</text>`:''}`;
const arrow=(x1,y1,x2,y2)=>`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#5d86ad" stroke-width="4"/><polygon points="${x2},${y2} ${x2-10},${y2-7} ${x2-10},${y2+7}" fill="#5d86ad"/>`;
const flow=(items)=>S(items.map((t,i)=>box(20+i*150,90,115,76,t)).join('')+items.slice(0,-1).map((_,i)=>arrow(136+i*150,128,163+i*150,128)).join(''),Math.max(640,items.length*150+20),250);
const timeline=(items)=>S(`<line x1="60" y1="145" x2="${80+(items.length-1)*150}" y2="145" stroke="#8ba4ba" stroke-width="5"/>`+items.map((t,i)=>`<circle cx="${70+i*150}" cy="145" r="15" fill="#fff" stroke="#315d86" stroke-width="4"/><text x="${70+i*150}" y="105" text-anchor="middle" class="v-label">${t}</text>`).join(''),Math.max(640,items.length*150),240);
const cards=(items,cols=2)=>{const cw=270,ch=94,g=20;const rows=Math.ceil(items.length/cols);return S(items.map((t,i)=>{const x=20+(i%cols)*(cw+g),y=20+Math.floor(i/cols)*(ch+g);return box(x,y,cw,ch,t[0],t[1]||'');}).join(''),cols*(cw+g)+20,rows*(ch+g)+20)};
const bars=(items,max=10)=>S(items.map((it,i)=>{const y=35+i*52;const w=400*(it[1]/max);return `<text x="20" y="${y+20}" class="v-label">${it[0]}</text><rect x="150" y="${y}" width="420" height="28" rx="8" fill="#eef3f7"/><rect x="150" y="${y}" width="${w}" height="28" rx="8" fill="#6f93b5"/><text x="580" y="${y+20}" class="v-label">${it[1]}</text>`;}).join(''),640,items.length*52+30);
const miniTable=(headers,rows)=>{const cols=headers.length,cw=145,rh=54,w=cols*cw+20,h=(rows.length+1)*rh+20;let out='';headers.forEach((t,i)=>{out+=`<rect x="${10+i*cw}" y="10" width="${cw}" height="${rh}" fill="#dceaf5" stroke="#9eb3c7"/><text x="${10+i*cw+cw/2}" y="43" text-anchor="middle" class="v-label">${t}</text>`;});rows.forEach((row,r)=>row.forEach((t,c)=>{out+=`<rect x="${10+c*cw}" y="${10+(r+1)*rh}" width="${cw}" height="${rh}" fill="#fff" stroke="#9eb3c7"/><text x="${10+c*cw+cw/2}" y="${43+(r+1)*rh}" text-anchor="middle" class="v-small">${t}</text>`;}));return S(out,w,h)};
const dots=(n,perRow=5)=>{let out='';for(let i=0;i<n;i++){const x=50+(i%perRow)*55,y=50+Math.floor(i/perRow)*55;out+=`<circle cx="${x}" cy="${y}" r="16" fill="#8fb2cf"/>`;}return S(out,Math.max(360,perRow*55+70),Math.ceil(n/perRow)*55+80)};
const map4=(labels)=>S(`<rect x="40" y="30" width="520" height="220" rx="18" fill="#f7fafc" stroke="#9eb3c7" stroke-width="2"/><line x1="300" y1="30" x2="300" y2="250" stroke="#c9d5df" stroke-width="3"/><line x1="40" y1="140" x2="560" y2="140" stroke="#c9d5df" stroke-width="3"/>`+
  [[170,88],[430,88],[170,198],[430,198]].map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="28" fill="#e9f4ff" stroke="#5d86ad" stroke-width="2"/><text x="${p[0]}" y="${p[1]+5}" text-anchor="middle" class="v-small">${labels[i]}</text>`).join(''),600,280);

window.AML_KIDS_VISUAL_DATA={
chinese:[
{id:'c01',tag:'事件順序',q:'看圖中的事件流程，哪一項最適合放在「？」的位置？',svg:flow(['忘記帶傘','？','回家換衣服']),alt:'流程圖依序是忘記帶傘、問號、回家換衣服。',caption:'事件流程圖',o:['天空放晴','淋到雨','買了一本書','朋友來訪'],a:1,e:'忘記帶傘後若遇雨，最合理的中間事件是淋到雨，再回家換衣服。',hint:'想一想前後事件的因果。'},
{id:'c02',tag:'人物情緒',q:'哪一個表情最符合「緊張又有些擔心」？',svg:cards([['🙂','嘴角上揚'],['😰','冒汗、皺眉'],['😴','閉眼想睡'],['😠','眉毛壓低']]),alt:'四個表情依序是微笑、冒汗皺眉、想睡、憤怒。',caption:'四種人物表情',o:['微笑','冒汗皺眉','想睡','生氣'],a:1,e:'冒汗與皺眉常是緊張、擔心的視覺線索。',hint:'觀察眉毛、眼睛與汗滴。'},
{id:'c03',tag:'段落結構',q:'這張結構圖最接近哪一種段落組織？',svg:S(box(210,20,220,70,'海岸很有特色')+box(35,155,160,70,'天空','顏色變化')+box(240,155,160,70,'海面','浪聲起伏')+box(445,155,160,70,'礁石','形狀多樣')+arrow(320,90,115,150)+arrow(320,90,320,150)+arrow(320,90,525,150),640,260),alt:'上方一個總述「海岸很有特色」，下方分成天空、海面、礁石三個細節。',caption:'總述與細節結構圖',o:['因果','總—分','時間順序','問題—解答'],a:1,e:'先提出整體特色，再分別說明三個細節，屬於總—分結構。',hint:'先看上方是否在概括下方內容。'},
{id:'c04',tag:'因果判斷',q:'根據圖中的箭頭，哪一句最能完整表達因果？',svg:flow(['豪雨','河水暴漲','道路積水']),alt:'流程依序是豪雨、河水暴漲、道路積水。',caption:'因果流程圖',o:['因為道路積水，所以開始豪雨','豪雨可能使河水暴漲，進而造成道路積水','河水暴漲和豪雨完全無關','道路積水一定會造成豪雨'],a:1,e:'圖示呈現由豪雨到河水暴漲，再到道路積水的因果鏈。',hint:'箭頭方向代表事件先後與影響。'},
{id:'c05',tag:'時間順序',q:'這篇遊記若依圖中的時間安排，哪一段最可能排在最後？',svg:timeline(['清晨','中午','傍晚','夜晚']),alt:'時間軸由左至右是清晨、中午、傍晚、夜晚。',caption:'一天的時間軸',o:['清晨看日出','中午吃午餐','傍晚走到海邊','夜晚回到旅館'],a:3,e:'時間軸最右側是夜晚，因此夜晚回到旅館最可能排在最後。',hint:'依時間軸由左到右閱讀。'},
{id:'c06',tag:'主旨整合',q:'圖中央最適合填入哪個主旨？',svg:S(box(215,95,210,80,'？')+box(25,20,160,60,'守信')+box(25,190,160,60,'主動補救')+box(455,20,160,60,'承擔後果')+box(455,190,160,60,'完成承諾')+arrow(185,50,220,105)+arrow(185,220,220,160)+arrow(455,50,420,105)+arrow(455,220,420,160),640,280),alt:'四個細節守信、主動補救、承擔後果、完成承諾都連向中央問號。',caption:'細節與主旨關係圖',o:['如何快速完成工作','對自己的行動與承諾負責','朋友一定要互相幫忙','犯錯後不要再提'],a:1,e:'四個細節共同指向「負責任」這個核心主旨。',hint:'找能同時涵蓋四個細節的選項。'},
{id:'c07',tag:'事實與觀點',q:'四張卡片中，哪一張最明顯屬於「可查證的事實」？',svg:cards([['這棟樓有12層','可數樓層'],['這棟樓最漂亮','個人評價'],['我最喜歡這裡','個人感受'],['這裡一定最棒','主觀判斷']]),alt:'四張卡片分別寫這棟樓有12層、最漂亮、我最喜歡、一定最棒。',caption:'四種敘述',o:['這棟樓有12層','這棟樓最漂亮','我最喜歡這裡','這裡一定最棒'],a:0,e:'樓層數可以實際計數或查資料驗證，屬於可查證事實。',hint:'想想哪一句可以用資料驗證。'},
{id:'c08',tag:'文化比較',q:'比較兩種節慶飲食時，哪一種整理方式最公平？',svg:miniTable(['比較欄位','A地','B地'],[['主要材料','米','麵'],['做法','蒸','煮'],['場合','節慶','節慶']]),alt:'表格以相同三個欄位比較A地與B地：主要材料、做法、場合。',caption:'文化比較表',o:['只描述自己熟悉的一方','用相同欄位比較兩地材料、做法與場合','用喜不喜歡判斷哪一方比較好','只比較名稱長短'],a:1,e:'使用相同欄位能讓文化比較建立在一致標準上。',hint:'公平比較要用相同的觀察欄位。'},
{id:'c09',tag:'詩歌意象',q:'哪一個感官最容易從這張圖像聯想到「浪聲一波波敲著岸邊」？',svg:S(`<path d="M40 170 Q120 110 200 170 T360 170 T520 170" fill="none" stroke="#5d86ad" stroke-width="10"/><path d="M40 205 Q120 145 200 205 T360 205 T520 205" fill="none" stroke="#8fb2cf" stroke-width="7"/><text x="300" y="70" text-anchor="middle" class="v-label">海浪拍岸</text>`,600,250),alt:'兩道波浪線向岸邊起伏，文字標示海浪拍岸。',caption:'海浪拍岸示意',o:['聽覺','嗅覺','味覺','觸覺'],a:0,e:'「浪聲」直接連結到聽覺，圖像也呈現海浪拍岸的情境。',hint:'題目中的「聲」是哪一種感官？'},
{id:'c10',tag:'人物觀點',q:'兩位人物看到同一活動卻有不同想法，最合理的解釋是什麼？',svg:cards([['甲：希望活動熱鬧','喜歡多人互動'],['乙：希望安靜一些','需要較少刺激']]),alt:'甲希望活動熱鬧，乙希望安靜一些。',caption:'兩種不同需求',o:['其中一人一定說謊','兩人需求不同，所以觀點可能不同','只有先說話的人才正確','不同意見代表無法合作'],a:1,e:'不同需求與經驗會形成不同觀點，並不表示一定有人錯。',hint:'先區分「觀點不同」和「誰對誰錯」。'}
],
english:[
{id:'e01',tag:'Schedule',q:'Look at the schedule. What class does Mia have on Thursday?',svg:miniTable(['Day','Class 1','Class 2'],[['Monday','Math','PE'],['Thursday','English','Art'],['Friday','Science','Music']]),alt:'Schedule: Monday Math and PE; Thursday English and Art; Friday Science and Music.',caption:'Weekly class schedule',o:['PE','English','Science','Music'],a:1,e:'Thursday shows English and Art, so English is correct.',hint:'Find Thursday first, then read across the row.'},
{id:'e02',tag:'Map',q:'The museum is in the top-right corner. Which place is it?',svg:map4(['Bank','Museum','Park','School']),alt:'A simple map: Bank top-left, Museum top-right, Park bottom-left, School bottom-right.',caption:'Town map',o:['Bank','Museum','Park','School'],a:1,e:'The top-right place on the map is the Museum.',hint:'Use the position clue: top-right.'},
{id:'e03',tag:'How many',q:'How many monkeys are there?',svg:S([70,160,250,340,430].map(x=>`<text x="${x}" y="150" font-size="54">🐒</text>`).join(''),560,220),alt:'Five monkey icons are shown.',caption:'Count the animals',o:['Three','Four','Five','Six'],a:2,e:'There are five monkey icons.',hint:'Count each monkey once.'},
{id:'e04',tag:'There is / are',q:'Which sentence best matches the picture?',svg:S(`<text x="250" y="150" font-size="82">🦁</text>`,600,230),alt:'One lion is shown.',caption:'One lion',o:['There are one lion.','There is one lion.','There are lions two.','There is two lions.'],a:1,e:'One singular animal uses There is: There is one lion.',hint:'One = singular.'},
{id:'e05',tag:'Destination',q:'Nina is at School and follows the arrow. Where is she going?',svg:S(`${box(40,90,150,70,'School')}${arrow(190,125,420,125)}${box(430,90,150,70,'Park')}`,620,240),alt:'School is on the left, an arrow points right to Park.',caption:'Route from School to Park',o:['She is going to the bank.','She is going to the park.','She is going to the museum.','She is going to school.'],a:1,e:'The arrow starts at School and points to Park.',hint:'Follow the arrow to its destination.'},
{id:'e06',tag:'Day',q:'Today is the highlighted day. What day is today?',svg:miniTable(['Mon','Tue','Wed','Thu'],[['○','○','★','○']]),alt:'A four-day row shows Monday, Tuesday, Wednesday, Thursday; a star is under Wednesday.',caption:'Calendar row',o:['Monday','Tuesday','Wednesday','Thursday'],a:2,e:'The star is under Wednesday.',hint:'Match the star with the day above it.'},
{id:'e07',tag:'Phonics',q:'What do these three words have in common?',svg:cards([['note','o_e'],['boat','oa'],['row','ow']],3),alt:'Three word cards: note with o_e, boat with oa, row with ow.',caption:'Long-o spelling patterns',o:['They all use exactly the same spelling.','They can share the /oʊ/ sound with different spellings.','They are all animal words.','They all end with the same letter.'],a:1,e:'note, boat, and row can share the long-o sound using different spelling patterns.',hint:'Compare sound and spelling separately.'},
{id:'e08',tag:'Place clues',q:'Which place best matches the picture clue “exhibits”?',svg:cards([['🏦','Bank'],['🏛️','Museum'],['🌳','Park'],['🏥','Hospital']],2),alt:'Four place icons: bank, museum, park, hospital.',caption:'Places in town',o:['Bank','Museum','Park','Hospital'],a:1,e:'A museum is the place most directly associated with exhibits.',hint:'Where do people usually see exhibits?'},
{id:'e09',tag:'Location',q:'The bank is on Red Street. Which marker shows the bank?',svg:S(`<line x1="60" y1="145" x2="560" y2="145" stroke="#b54b4b" stroke-width="18"/><text x="310" y="115" text-anchor="middle" class="v-label">Red Street</text><circle cx="440" cy="145" r="25" fill="#fff" stroke="#20324a" stroke-width="3"/><text x="440" y="152" text-anchor="middle" class="v-label">B</text><circle cx="170" cy="145" r="25" fill="#fff" stroke="#20324a" stroke-width="3"/><text x="170" y="152" text-anchor="middle" class="v-label">A</text>`,620,240),alt:'Red Street is a horizontal road. Marker A and marker B are both on the road; B is labeled as the bank location in the clue.',caption:'Red Street map',o:['Marker A','Marker B','Neither marker','Both are museums'],a:1,e:'The clue identifies the bank location as marker B on Red Street.',hint:'Use the labeled marker from the clue.'},
{id:'e10',tag:'Schedule comparison',q:'Which day has both Math and PE?',svg:miniTable(['Day','Math','PE'],[['Mon','✓','✓'],['Tue','✓','—'],['Wed','—','✓']]),alt:'Table: Monday has Math and PE; Tuesday has Math only; Wednesday has PE only.',caption:'Class comparison table',o:['Monday','Tuesday','Wednesday','No day'],a:0,e:'Monday has check marks in both Math and PE.',hint:'Find the row with two check marks.'}
],
math:[],
science:[],
social:[]
};
})();