(function(){
const KEY='seraNationalExamV1';
const qs=window.SERA_EXAM_QUESTIONS||[];
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"answers":{},"wrong":[]}')}catch(e){return{answers:{},wrong:[]}}}
function write(s){localStorage.setItem(KEY,JSON.stringify(s))}
function record(q,choice){const s=read();const correct=choice===q.answer;s.answers[q.id]={choice,correct,topic:q.topic,at:new Date().toISOString()};const set=new Set(s.wrong||[]);correct?set.delete(q.id):set.add(q.id);s.wrong=[...set];write(s);return correct}
function dashboard(){const totalEl=document.getElementById('totalAnswered');if(!totalEl)return;const s=read(), vals=Object.values(s.answers||{}), correct=vals.filter(x=>x.correct).length;totalEl.textContent=vals.length;document.getElementById('accuracy').textContent=vals.length?Math.round(correct/vals.length*100)+'%':'—';document.getElementById('wrongCount').textContent=(s.wrong||[]).length;document.getElementById('wrongSummary').textContent=(s.wrong||[]).length?`目前有 ${(s.wrong||[]).length} 題需要再練。答對後會自動移出錯題清單。`:'目前還沒有錯題。開始練習後，系統會自動整理。';const groups={};vals.forEach(v=>{groups[v.topic] ||= {n:0,c:0};groups[v.topic].n++;if(v.correct)groups[v.topic].c++});const box=document.getElementById('topicStats');if(!Object.keys(groups).length){box.innerHTML='<div class="empty">完成幾題後，這裡會顯示各主題正確率。</div>';return}box.innerHTML=Object.entries(groups).map(([k,v])=>`<div class="topic-row"><span>${k}<br><span class="small">${v.n} 題紀錄</span></span><strong>${Math.round(v.c/v.n*100)}%</strong></div>`).join('')}
function practice(){const stem=document.getElementById('stem');if(!stem)return;const params=new URLSearchParams(location.search),wrongMode=params.get('mode')==='wrong',state=read();let pool=wrongMode?qs.filter(q=>(state.wrong||[]).includes(q.id)):qs.slice();document.getElementById('modeLabel').textContent=wrongMode?'Error Review':'Demo Practice';if(!pool.length){document.getElementById('questionCard').style.display='none';const e=document.getElementById('emptyState');e.style.display='block';e.innerHTML=wrongMode?'目前沒有待複習錯題。<br><a class="exam-btn" style="margin-top:12px" href="./practice.html">改做示範練習 →</a>':'目前沒有題目。';return}
let i=0,selected=null,locked=false;const els={counter:document.getElementById('counter'),bar:document.getElementById('progressBar'),year:document.getElementById('yearTag'),topic:document.getElementById('topicTag'),stem,options:document.getElementById('options'),submit:document.getElementById('submitBtn'),panel:document.getElementById('answerPanel'),title:document.getElementById('resultTitle'),explain:document.getElementById('explanation'),diff:document.getElementById('differences'),mem:document.getElementById('memoryTip'),trap:document.getElementById('trap'),next:document.getElementById('nextBtn'),ai:document.getElementById('aiBtn')};
function render(){selected=null;locked=false;const q=pool[i];els.counter.textContent=`第 ${i+1} 題 / ${pool.length} 題`;els.bar.style.width=`${i/pool.length*100}%`;els.year.textContent=q.year;els.topic.textContent=q.topic;els.stem.textContent=q.stem;els.panel.classList.remove('show');els.submit.disabled=true;els.submit.style.display='inline-flex';els.options.innerHTML='';q.options.forEach((t,idx)=>{const b=document.createElement('button');b.className='option';b.innerHTML=`<strong>${String.fromCharCode(65+idx)}.</strong><span>${t}</span>`;b.onclick=()=>{if(locked)return;selected=idx;[...els.options.children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');els.submit.disabled=false};els.options.appendChild(b)});els.next.textContent=i===pool.length-1?'完成本輪 →':'下一題 →';if(window.SeraLearningTrace)window.SeraLearningTrace.updateProgress(Math.round(i/pool.length*100))}
els.submit.onclick=()=>{if(selected===null||locked)return;locked=true;const q=pool[i],ok=record(q,selected);[...els.options.children].forEach((b,idx)=>{if(idx===q.answer)b.classList.add('correct');else if(idx===selected)b.classList.add('wrong')});els.title.textContent=ok?'✓ 答對了':'這題值得再練一次';els.explain.textContent=q.explanation;els.diff.innerHTML=q.differences.map(x=>`<li>${x}</li>`).join('');els.mem.textContent=q.memoryTip;els.trap.textContent=q.trap;els.panel.classList.add('show');els.submit.style.display='none'};
els.next.onclick=()=>{if(i<pool.length-1){i++;render();scrollTo({top:0,behavior:'smooth'})}else{if(window.SeraLearningTrace)window.SeraLearningTrace.complete();location.href='./index.html'}};
els.ai.onclick=async()=>{const q=pool[i];const prompt=`我正在準備職能治療師國考精神領域。以下是我剛才練習的題目：\n\n${q.stem}\n${q.options.map((x,n)=>String.fromCharCode(65+n)+'. '+x).join('\n')}\n\n正確答案：${String.fromCharCode(65+q.answer)}；我選擇：${String.fromCharCode(65+selected)}。\n\n請以資深精神領域職能治療師與國考教師角色：\n1. 解釋正確答案為什麼正確\n2. 比較我選的答案與正解最容易混淆之處\n3. 指出題幹應抓的關鍵字\n4. 提供容易記憶的方法\n5. 再出一題相似概念、不同情境的單選題測試我\n6. 先不要公布新題答案，等我作答。`;try{await navigator.clipboard.writeText(prompt);els.ai.textContent='已複製 ✓';setTimeout(()=>els.ai.textContent='複製 AI 精解提示',1800)}catch(e){alert(prompt)}};render()}
document.addEventListener('DOMContentLoaded',()=>{dashboard();practice()});
})();
